### ISSUE TITLE
idea humans.txt

### ISSUE THREAD

**Issue by bnomei** [jenstornell/kirby-robots-writer#2]
maybe you could dublicate your repo for humans.txt. would feel like stealing if i would do it. ;)

http://humanstxt.org/

**Comment by jenstornell** [comment]
Or maybe just add support for humans.txt with this plugin. It's only 12 rows of code and it would require 2-3 more rows for humans.txt to be included.

https://github.com/jenstornell/kirby-robots-writer/blob/master/kirby-robots-writer.php#L6
