### ISSUE TITLE
Please Upgrade to Kirby 3 😊

### ISSUE THREAD

**Issue by luxlogica** [jenstornell/kirby-robots-writer#3]

**Comment by bnomei** [comment]
i did a PR for that https://github.com/jenstornell/kirby-robots-writer/pull/4

**Comment by bnomei** [comment]
@luxlogica i inherited the repo. you can get a quick snapshot for k3 using the kirby3 branch. i will add compser support at some point later, but not within next month or so.

https://github.com/bnomei/kirby-robots-writer/tree/kirby-3

**Comment by bnomei** [comment]
what i mean is that the composer json etc are still configured for jens and no entry to packagist exists yet.

**Comment by bnomei** [comment]
i inherited this k2 repo and created a new repo for k3 version.
https://github.com/bnomei/kirby3-robots-txt
